import type { FoodDatabase } from './types.js';

/**
 * Offline bilingual catalogue. Values are per 100 g.
 *
 * Staple ingredients are derived from USDA FoodData Central (public domain,
 * CC0 1.0): energy 1008, protein 1003, total lipid 1004, carbohydrate by
 * difference 1005, plus fiber/sugars/saturated-fat/sodium (RFC 0024). Common
 * Chinese dishes that FDC does not cover are marked `curated` (reasonable
 * kitchen estimates, including salt/soy sodium). See README for attribution.
 */
export const foods: FoodDatabase = [
  // ---- Staples & grains (USDA) ----
  {
    id: 'usda-white-rice',
    name: { en: 'White rice, cooked', 'zh-CN': '白米饭' },
    kcal: 130,
    macros: { proteinG: 2.7, carbsG: 28, fatG: 0.3 },
    micros: { fiberG: 0.4, sugarG: 0.1, saturatedFatG: 0.1, sodiumMg: 2 },
    defaultGrams: 200,
    source: 'usda-fdc',
  },
  {
    id: 'usda-brown-rice',
    name: { en: 'Brown rice, cooked', 'zh-CN': '糙米饭' },
    kcal: 112,
    macros: { proteinG: 2.6, carbsG: 23.8, fatG: 0.9 },
    micros: { fiberG: 1.6, sugarG: 0.2, saturatedFatG: 0.2, sodiumMg: 4 },
    defaultGrams: 200,
    source: 'usda-fdc',
  },
  {
    id: 'usda-pasta',
    name: { en: 'Pasta, cooked', 'zh-CN': '意面（熟）' },
    kcal: 131,
    macros: { proteinG: 5, carbsG: 25, fatG: 1.1 },
    micros: { fiberG: 1.8, sugarG: 0.6, saturatedFatG: 0.1, sodiumMg: 1 },
    defaultGrams: 200,
    source: 'usda-fdc',
  },
  {
    id: 'usda-oats',
    name: { en: 'Rolled oats, dry', 'zh-CN': '燕麦片（干）' },
    kcal: 380,
    macros: { proteinG: 13, carbsG: 66, fatG: 7 },
    micros: { fiberG: 10.1, sugarG: 1, saturatedFatG: 1.2, sodiumMg: 5 },
    defaultGrams: 50,
    source: 'usda-fdc',
  },
  {
    id: 'usda-whole-wheat-bread',
    name: { en: 'Whole wheat bread', 'zh-CN': '全麦面包' },
    kcal: 247,
    macros: { proteinG: 13, carbsG: 41, fatG: 3.4 },
    micros: { fiberG: 7, sugarG: 6, saturatedFatG: 0.9, sodiumMg: 400 },
    defaultGrams: 60,
    source: 'usda-fdc',
  },
  {
    id: 'usda-potato',
    name: { en: 'Potato, baked', 'zh-CN': '烤土豆' },
    kcal: 93,
    macros: { proteinG: 2.5, carbsG: 21, fatG: 0.1 },
    micros: { fiberG: 2.1, sugarG: 1.1, saturatedFatG: 0, sodiumMg: 10 },
    defaultGrams: 200,
    source: 'usda-fdc',
  },
  {
    id: 'usda-sweet-potato',
    name: { en: 'Sweet potato, baked', 'zh-CN': '红薯' },
    kcal: 90,
    macros: { proteinG: 2, carbsG: 21, fatG: 0.1 },
    micros: { fiberG: 3, sugarG: 6.5, saturatedFatG: 0, sodiumMg: 36 },
    defaultGrams: 200,
    source: 'usda-fdc',
  },
  {
    id: 'usda-corn',
    name: { en: 'Sweet corn', 'zh-CN': '甜玉米' },
    kcal: 86,
    macros: { proteinG: 3.2, carbsG: 19, fatG: 1.4 },
    micros: { fiberG: 2.7, sugarG: 6.3, saturatedFatG: 0.2, sodiumMg: 1 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },

  // ---- Protein (USDA) ----
  {
    id: 'usda-chicken-breast',
    name: { en: 'Chicken breast, cooked', 'zh-CN': '鸡胸肉（熟）' },
    kcal: 165,
    macros: { proteinG: 31, carbsG: 0, fatG: 3.6 },
    micros: { fiberG: 0, sugarG: 0, saturatedFatG: 1, sodiumMg: 74 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-lean-beef',
    name: { en: 'Lean beef, cooked', 'zh-CN': '瘦牛肉（熟）' },
    kcal: 217,
    macros: { proteinG: 26, carbsG: 0, fatG: 12 },
    micros: { fiberG: 0, sugarG: 0, saturatedFatG: 3.5, sodiumMg: 60 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-pork-tenderloin',
    name: { en: 'Pork tenderloin, cooked', 'zh-CN': '猪里脊（熟）' },
    kcal: 187,
    macros: { proteinG: 26, carbsG: 0, fatG: 8 },
    micros: { fiberG: 0, sugarG: 0, saturatedFatG: 1.4, sodiumMg: 60 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-salmon',
    name: { en: 'Salmon, cooked', 'zh-CN': '三文鱼（熟）' },
    kcal: 208,
    macros: { proteinG: 20, carbsG: 0, fatG: 13 },
    micros: { fiberG: 0, sugarG: 0, saturatedFatG: 3, sodiumMg: 50 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-tuna',
    name: { en: 'Tuna, canned in water', 'zh-CN': '水浸金枪鱼' },
    kcal: 116,
    macros: { proteinG: 25.5, carbsG: 0, fatG: 1 },
    micros: { fiberG: 0, sugarG: 0, saturatedFatG: 0.2, sodiumMg: 300 },
    defaultGrams: 100,
    source: 'usda-fdc',
  },
  {
    id: 'usda-shrimp',
    name: { en: 'Shrimp, cooked', 'zh-CN': '虾仁（熟）' },
    kcal: 99,
    macros: { proteinG: 24, carbsG: 0.2, fatG: 0.3 },
    micros: { fiberG: 0, sugarG: 0, saturatedFatG: 0.1, sodiumMg: 111 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-egg',
    name: { en: 'Egg, whole', 'zh-CN': '鸡蛋' },
    kcal: 155,
    macros: { proteinG: 13, carbsG: 1.1, fatG: 11 },
    micros: { fiberG: 0, sugarG: 0.6, saturatedFatG: 3.3, sodiumMg: 124 },
    defaultGrams: 50,
    source: 'usda-fdc',
  },
  {
    id: 'usda-egg-white',
    name: { en: 'Egg white', 'zh-CN': '蛋白' },
    kcal: 52,
    macros: { proteinG: 11, carbsG: 0.7, fatG: 0.2 },
    micros: { fiberG: 0, sugarG: 0.7, saturatedFatG: 0, sodiumMg: 166 },
    defaultGrams: 50,
    source: 'usda-fdc',
  },
  {
    id: 'usda-tofu',
    name: { en: 'Tofu, firm', 'zh-CN': '北豆腐' },
    kcal: 144,
    macros: { proteinG: 17, carbsG: 3, fatG: 9 },
    micros: { fiberG: 2.3, sugarG: 0.6, saturatedFatG: 1.3, sodiumMg: 10 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },

  // ---- Dairy (USDA) ----
  {
    id: 'usda-whole-milk',
    name: { en: 'Whole milk', 'zh-CN': '全脂牛奶' },
    kcal: 61,
    macros: { proteinG: 3.2, carbsG: 4.8, fatG: 3.3 },
    micros: { fiberG: 0, sugarG: 5.1, saturatedFatG: 1.9, sodiumMg: 43 },
    defaultGrams: 250,
    source: 'usda-fdc',
  },
  {
    id: 'usda-greek-yogurt',
    name: { en: 'Greek yogurt, plain nonfat', 'zh-CN': '脱脂希腊酸奶' },
    kcal: 59,
    macros: { proteinG: 10, carbsG: 3.6, fatG: 0.4 },
    micros: { fiberG: 0, sugarG: 4, saturatedFatG: 0, sodiumMg: 40 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-cottage-cheese',
    name: { en: 'Cottage cheese, low fat', 'zh-CN': '低脂茅屋奶酪' },
    kcal: 72,
    macros: { proteinG: 12, carbsG: 5, fatG: 1 },
    micros: { fiberG: 0, sugarG: 2.6, saturatedFatG: 0.8, sodiumMg: 350 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-cheddar',
    name: { en: 'Cheddar cheese', 'zh-CN': '切达奶酪' },
    kcal: 403,
    macros: { proteinG: 23, carbsG: 1.3, fatG: 33 },
    micros: { fiberG: 0, sugarG: 0.5, saturatedFatG: 19, sodiumMg: 620 },
    defaultGrams: 30,
    source: 'usda-fdc',
  },

  // ---- Vegetables & fruit (USDA) ----
  {
    id: 'usda-broccoli',
    name: { en: 'Broccoli', 'zh-CN': '西兰花' },
    kcal: 34,
    macros: { proteinG: 2.8, carbsG: 7, fatG: 0.4 },
    micros: { fiberG: 2.6, sugarG: 1.7, saturatedFatG: 0.1, sodiumMg: 40 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-spinach',
    name: { en: 'Spinach', 'zh-CN': '菠菜' },
    kcal: 23,
    macros: { proteinG: 2.9, carbsG: 3.6, fatG: 0.4 },
    micros: { fiberG: 2.2, sugarG: 0.4, saturatedFatG: 0.1, sodiumMg: 80 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-cabbage',
    name: { en: 'Cabbage', 'zh-CN': '卷心菜' },
    kcal: 25,
    macros: { proteinG: 1.3, carbsG: 5.8, fatG: 0.1 },
    micros: { fiberG: 2.3, sugarG: 3.2, saturatedFatG: 0, sodiumMg: 18 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-mushroom',
    name: { en: 'Mushrooms', 'zh-CN': '蘑菇' },
    kcal: 22,
    macros: { proteinG: 3.1, carbsG: 3.3, fatG: 0.3 },
    micros: { fiberG: 1.5, sugarG: 1.7, saturatedFatG: 0.1, sodiumMg: 5 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-carrot',
    name: { en: 'Carrots', 'zh-CN': '胡萝卜' },
    kcal: 41,
    macros: { proteinG: 0.9, carbsG: 9.6, fatG: 0.2 },
    micros: { fiberG: 2.8, sugarG: 4.7, saturatedFatG: 0, sodiumMg: 69 },
    defaultGrams: 100,
    source: 'usda-fdc',
  },
  {
    id: 'usda-tomato',
    name: { en: 'Tomatoes', 'zh-CN': '番茄' },
    kcal: 18,
    macros: { proteinG: 0.9, carbsG: 3.9, fatG: 0.2 },
    micros: { fiberG: 1.2, sugarG: 2.6, saturatedFatG: 0, sodiumMg: 5 },
    defaultGrams: 150,
    source: 'usda-fdc',
  },
  {
    id: 'usda-lettuce',
    name: { en: 'Lettuce', 'zh-CN': '生菜' },
    kcal: 15,
    macros: { proteinG: 1.4, carbsG: 2.9, fatG: 0.2 },
    micros: { fiberG: 1.3, sugarG: 0.8, saturatedFatG: 0, sodiumMg: 10 },
    defaultGrams: 100,
    source: 'usda-fdc',
  },
  {
    id: 'usda-banana',
    name: { en: 'Banana', 'zh-CN': '香蕉' },
    kcal: 89,
    macros: { proteinG: 1.1, carbsG: 23, fatG: 0.3 },
    micros: { fiberG: 2.6, sugarG: 12.2, saturatedFatG: 0.1, sodiumMg: 1 },
    defaultGrams: 120,
    source: 'usda-fdc',
  },
  {
    id: 'usda-apple',
    name: { en: 'Apple', 'zh-CN': '苹果' },
    kcal: 52,
    macros: { proteinG: 0.3, carbsG: 14, fatG: 0.2 },
    micros: { fiberG: 2.4, sugarG: 10.4, saturatedFatG: 0, sodiumMg: 1 },
    defaultGrams: 180,
    source: 'usda-fdc',
  },
  {
    id: 'usda-avocado',
    name: { en: 'Avocado', 'zh-CN': '牛油果' },
    kcal: 160,
    macros: { proteinG: 2, carbsG: 8.5, fatG: 14.7 },
    micros: { fiberG: 6.7, sugarG: 0.7, saturatedFatG: 2.1, sodiumMg: 7 },
    defaultGrams: 80,
    source: 'usda-fdc',
  },

  // ---- Nuts, fats & staples (USDA) ----
  {
    id: 'usda-almonds',
    name: { en: 'Almonds', 'zh-CN': '杏仁' },
    kcal: 579,
    macros: { proteinG: 21, carbsG: 22, fatG: 50 },
    micros: { fiberG: 12.5, sugarG: 4.4, saturatedFatG: 3.8, sodiumMg: 1 },
    defaultGrams: 20,
    source: 'usda-fdc',
  },
  {
    id: 'usda-peanut-butter',
    name: { en: 'Peanut butter', 'zh-CN': '花生酱' },
    kcal: 588,
    macros: { proteinG: 25, carbsG: 20, fatG: 50 },
    micros: { fiberG: 6, sugarG: 9, saturatedFatG: 10, sodiumMg: 450 },
    defaultGrams: 20,
    source: 'usda-fdc',
  },
  {
    id: 'usda-olive-oil',
    name: { en: 'Olive oil', 'zh-CN': '橄榄油' },
    kcal: 884,
    macros: { proteinG: 0, carbsG: 0, fatG: 100 },
    micros: { fiberG: 0, sugarG: 0, saturatedFatG: 13.8, sodiumMg: 2 },
    defaultGrams: 10,
    source: 'usda-fdc',
  },

  // ---- Common Chinese dishes (curated estimates) ----
  {
    id: 'curated-tomato-egg',
    name: { en: 'Tomato scrambled egg', 'zh-CN': '番茄炒蛋' },
    kcal: 110,
    macros: { proteinG: 5, carbsG: 5, fatG: 7 },
    micros: { fiberG: 0.8, sugarG: 3, saturatedFatG: 1.5, sodiumMg: 400 },
    defaultGrams: 200,
    source: 'curated',
  },
  {
    id: 'curated-kung-pao-chicken',
    name: { en: 'Kung Pao chicken', 'zh-CN': '宫保鸡丁' },
    kcal: 160,
    macros: { proteinG: 11, carbsG: 9, fatG: 9 },
    micros: { fiberG: 1.5, sugarG: 8, saturatedFatG: 1.5, sodiumMg: 600 },
    defaultGrams: 200,
    source: 'curated',
  },
  {
    id: 'curated-shredded-pork-pepper',
    name: { en: 'Shredded pork with pepper', 'zh-CN': '青椒肉丝' },
    kcal: 150,
    macros: { proteinG: 12, carbsG: 6, fatG: 9 },
    micros: { fiberG: 1.2, sugarG: 3, saturatedFatG: 1.5, sodiumMg: 550 },
    defaultGrams: 200,
    source: 'curated',
  },
  {
    id: 'curated-mapo-tofu',
    name: { en: 'Mapo tofu', 'zh-CN': '麻婆豆腐' },
    kcal: 140,
    macros: { proteinG: 9, carbsG: 5, fatG: 10 },
    micros: { fiberG: 1, sugarG: 2, saturatedFatG: 1.5, sodiumMg: 600 },
    defaultGrams: 200,
    source: 'curated',
  },
  {
    id: 'curated-braised-pork-belly',
    name: { en: 'Braised pork belly', 'zh-CN': '红烧肉' },
    kcal: 350,
    macros: { proteinG: 12, carbsG: 8, fatG: 30 },
    micros: { fiberG: 0.3, sugarG: 5, saturatedFatG: 10, sodiumMg: 500 },
    defaultGrams: 100,
    source: 'curated',
  },
  {
    id: 'curated-beef-noodle-soup',
    name: { en: 'Beef noodle soup', 'zh-CN': '牛肉面' },
    kcal: 120,
    macros: { proteinG: 7, carbsG: 14, fatG: 4 },
    micros: { fiberG: 1, sugarG: 2, saturatedFatG: 1.5, sodiumMg: 650 },
    defaultGrams: 400,
    source: 'curated',
  },
  {
    id: 'curated-pork-dumplings',
    name: { en: 'Pork dumplings', 'zh-CN': '猪肉饺子' },
    kcal: 220,
    macros: { proteinG: 9, carbsG: 24, fatG: 9 },
    micros: { fiberG: 1.5, sugarG: 2, saturatedFatG: 3, sodiumMg: 550 },
    defaultGrams: 150,
    source: 'curated',
  },
  {
    id: 'curated-steamed-bun',
    name: { en: 'Steamed pork bun', 'zh-CN': '肉包子' },
    kcal: 220,
    macros: { proteinG: 8, carbsG: 28, fatG: 9 },
    micros: { fiberG: 1.2, sugarG: 3, saturatedFatG: 3, sodiumMg: 350 },
    defaultGrams: 100,
    source: 'curated',
  },
  {
    id: 'curated-chow-mein',
    name: { en: 'Chow mein', 'zh-CN': '炒面' },
    kcal: 180,
    macros: { proteinG: 6, carbsG: 22, fatG: 8 },
    micros: { fiberG: 1.5, sugarG: 2, saturatedFatG: 1.5, sodiumMg: 550 },
    defaultGrams: 250,
    source: 'curated',
  },
  {
    id: 'curated-egg-fried-rice',
    name: { en: 'Egg fried rice', 'zh-CN': '蛋炒饭' },
    kcal: 170,
    macros: { proteinG: 5, carbsG: 24, fatG: 6 },
    micros: { fiberG: 0.8, sugarG: 1.5, saturatedFatG: 1.5, sodiumMg: 450 },
    defaultGrams: 250,
    source: 'curated',
  },
  {
    id: 'curated-steamed-fish',
    name: { en: 'Steamed fish', 'zh-CN': '清蒸鱼' },
    kcal: 110,
    macros: { proteinG: 16, carbsG: 1, fatG: 4 },
    micros: { fiberG: 0.2, sugarG: 1, saturatedFatG: 1, sodiumMg: 500 },
    defaultGrams: 150,
    source: 'curated',
  },
  {
    id: 'curated-broccoli-shrimp',
    name: { en: 'Broccoli with shrimp', 'zh-CN': '西兰花炒虾仁' },
    kcal: 95,
    macros: { proteinG: 10, carbsG: 5, fatG: 3 },
    micros: { fiberG: 1.8, sugarG: 2, saturatedFatG: 0.5, sodiumMg: 500 },
    defaultGrams: 200,
    source: 'curated',
  },
  {
    id: 'curated-cucumber-salad',
    name: { en: 'Garlic cucumber salad', 'zh-CN': '凉拌黄瓜' },
    kcal: 40,
    macros: { proteinG: 1, carbsG: 4, fatG: 2 },
    micros: { fiberG: 0.8, sugarG: 1.8, saturatedFatG: 0.3, sodiumMg: 450 },
    defaultGrams: 150,
    source: 'curated',
  },
  {
    id: 'curated-soy-milk',
    name: { en: 'Soy milk, unsweetened', 'zh-CN': '无糖豆浆' },
    kcal: 31,
    macros: { proteinG: 3, carbsG: 2, fatG: 1.6 },
    micros: { fiberG: 0.8, sugarG: 1, saturatedFatG: 0.3, sodiumMg: 15 },
    defaultGrams: 300,
    source: 'curated',
  },
  {
    id: 'curated-rice-congee',
    name: { en: 'Rice congee', 'zh-CN': '白粥' },
    kcal: 46,
    macros: { proteinG: 1.1, carbsG: 10, fatG: 0.1 },
    micros: { fiberG: 0.2, sugarG: 0.1, saturatedFatG: 0, sodiumMg: 2 },
    defaultGrams: 300,
    source: 'curated',
  },
];
