name: Feature request
description: Suggest an idea for LeanOn
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem, e.g. "I always struggle with ...".
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
  - type: dropdown
    id: willingness
    attributes:
      label: Are you willing to open an RFC / PR for this?
      options:
        - "Yes"
        - "No"
        - "Need guidance"
    validations:
      required: true
