import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = new URL('../', import.meta.url);
const mark = await readFile(new URL('assets/logo-mark.svg', root), 'utf8');
const mono = await readFile(new URL('assets/logo-monochrome.svg', root), 'utf8');
const paths = (svg) => [...svg.matchAll(/\bd="([^"]+)"/g)].map((match) => match[1]);
const heart = paths(mark);
assert.equal(heart.length, 2, 'Expected the existing two-part heart');
assert.deepEqual(paths(mono), heart, 'Color and monochrome silhouettes must agree');
assert.match(mark, /viewBox="0 0 1254 1254"/);

// AdaptiveIconDrawable shows the center 72dp of a 108dp layer. Map the
// measured heart to 80% of that visible area, not of the full layer. At this
// size its outer contour has ~0.48dp clearance inside the 66dp safe circle.
const scale = (72 * 0.8) / 1068;
const inset = 54 - 627 * scale;
const tileScale = (1254 * 0.8) / 1068;
const tileInset = 627 * (1 - tileScale);
const args = process.argv.slice(2);
assert(args.length === 0 || (args.length === 1 && args[0] === '--check'),
  'Usage: node scripts/generate-icons.mjs [--check]');

// Sample the canonical cubic silhouette against the 66dp safe-zone circle.
// Fail on new SVG commands rather than silently validating the wrong geometry.
let radius = 0;
for (const path of heart) {
  const tokens = path.match(/[A-Za-z]|-?\d+(?:\.\d+)?/g);
  let x = 0;
  let y = 0;
  for (let i = 0; i < tokens.length;) {
    const command = tokens[i++];
    if (command === 'M') {
      x = Number(tokens[i++]);
      y = Number(tokens[i++]);
    } else if (command === 'C') {
      const [x1, y1, x2, y2, x3, y3] = tokens.slice(i, i + 6).map(Number);
      i += 6;
      for (let step = 0; step <= 200; step++) {
        const t = step / 200;
        const u = 1 - t;
        const px = u ** 3 * x + 3 * u ** 2 * t * x1 + 3 * u * t ** 2 * x2 + t ** 3 * x3;
        const py = u ** 3 * y + 3 * u ** 2 * t * y1 + 3 * u * t ** 2 * y2 + t ** 3 * y3;
        radius = Math.max(radius, Math.hypot(inset + px * scale - 54, inset + py * scale - 54));
      }
      x = x3;
      y = y3;
    } else {
      assert.equal(command, 'Z', 'Update the geometry check for new path commands');
    }
  }
}
assert(radius < 33, `Heart exceeds the 33dp safe-zone radius: ${radius}`);

const drawable = (colors) => `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!-- Generated by scripts/generate-icons.mjs from assets/logo-mark.svg.
         Heart fills 80% of the central 72dp visible area; see RFC 0026. -->
    <group
        android:scaleX="${scale.toFixed(9)}"
        android:scaleY="${scale.toFixed(9)}"
        android:translateX="${inset.toFixed(9)}"
        android:translateY="${inset.toFixed(9)}">
${heart.map((path, index) => `        <path
            android:fillColor="${colors[index]}"
            android:pathData="${path}" />`).join('\n')}
    </group>
</vector>
`;

const save = async (relative, data) => {
  const url = new URL(relative, root);
  if (args[0] === '--check') {
    const actual = await readFile(url);
    const message = `Regenerate ${fileURLToPath(url)}`;
    if (relative.endsWith('.png')) {
      // Compare image content rather than platform-dependent PNG compression.
      const existing = sharp(actual);
      const expected = sharp(data);
      const a = await existing.metadata();
      const b = await expected.metadata();
      for (const key of ['format', 'width', 'height', 'channels', 'hasAlpha']) {
        assert.equal(a[key], b[key], message);
      }
      assert.deepEqual(await existing.raw().toBuffer(), await expected.raw().toBuffer(), message);
    } else {
      assert.deepEqual(actual, Buffer.from(data), message);
    }
  } else {
    await writeFile(url, data);
  }
};
for (const [name, colors] of [
  ['foreground', ['#58AB8D', '#218967']],
  ['monochrome', ['#FFFFFFFF', '#FFFFFFFF']],
]) {
  await save(`apps/android/app/src/main/res/drawable/ic_launcher_${name}.xml`, drawable(colors));
}
const transform = `translate(${tileInset.toFixed(9)} ${tileInset.toFixed(9)}) scale(${tileScale.toFixed(9)})`;
const logo = mark.replaceAll('eucalyptusMark', 'eucalyptus').replaceAll('botanicalMark', 'botanical')
  .replace('  <path', `  <rect width="1254" height="1254" rx="276" fill="#FFFFFF"/>\n  <g transform="${transform}">\n  <path`)
  .replace('</svg>', '  </g>\n</svg>');
const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1254 1254" fill="none" role="img" aria-label="LeanOn">
  <title>LeanOn</title>
  <rect width="1254" height="1254" fill="#218967"/>
  <g transform="${transform}">
    <path fill="#FFFFFF" d="${heart[0]}"/>
  </g>
</svg>
`;
await save('assets/logo.svg', logo);
await save('assets/favicon.svg', favicon);
const square = logo.replace(' rx="276"', '');
await save('assets/app-icon.png', await sharp(Buffer.from(square)).resize(1024, 1024).ensureAlpha().png({ compressionLevel: 9 }).toBuffer());
await save('assets/app-icon-ios-1024.png', await sharp(Buffer.from(square))
  .resize(1024, 1024).flatten({ background: '#FFFFFF' }).removeAlpha().png({ compressionLevel: 9 }).toBuffer());
console.log(`Icons ${args[0] === '--check' ? 'checked' : 'generated'}: 80% visible width; sampled safe-zone radius ${radius.toFixed(3)}dp < 33dp.`);
